### ISSUE TITLE
Insert google tag manager into app

### ISSUE THREAD

**Issue by devangrose** [devangrose/pamneighbors#1]
Check out https://www.npmjs.com/package/react-gtm-module

Add
```
import TagManager from 'react-gtm-module'
```
to imports in src/App.js

----------------------------------

Add 
 ```
const tagManagerArgs = {
    gtmId: 'GTM-000000',
    auth: '6sBOnZx1hqPcO01xPOytLK',
    preview: 'env-2'
}
 
TagManager.initialize(tagManagerArgs)
```
below imports but above app component stuff

**Comment by ryangrose** [comment]
Added in branch https://github.com/devangrose/pamneighbors/tree/google-tag-manager
